version: '3.8'

# access local Hanabira app on http://localhost:8888

services:
  frontend-next:
    build:
      context: ./frontend-next
    image: coil/hanabira.org:frontend-next
    environment:
      REACT_APP_HOST_IP: 'express-db'
      GA_MEASUREMENT_ID: '' # Google Analytics measurement ID 
    restart: unless-stopped
    networks:
      - hanabira-network

  express-db:
    build:
      context: ./backend/express
    image: coil/hanabira.org:express-db
    environment:
      REACT_APP_HOST_IP: 'express-db'
    restart: unless-stopped
    networks:
      - hanabira-network

  flask-dynamic-db:
    build:
      context: ./backend/flask
    image: coil/hanabira.org:flask-dynamic-db
    volumes:
      - ./user_db:/data/db
    restart: unless-stopped
    networks:
      - hanabira-network

  dictionary-db:
    build:
      context: ./backend/dictionary
    image: coil/hanabira.org:dictionary-db
    volumes:
      - './config_dummy.json:/app/config.json'
    restart: unless-stopped
    networks:
      - hanabira-network

  nginx:
    image: nginx:latest
    ports:
      - '8888:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - hanabira-network

volumes:
  user_db:

networks:
  hanabira-network: